-- AlterTable
ALTER TABLE "patients_health_data" ALTER COLUMN "hasAllergies" DROP NOT NULL,
ALTER COLUMN "hasAllergies" SET DEFAULT false,
ALTER COLUMN "hasDiabetes" DROP NOT NULL,
ALTER COLUMN "hasDiabetes" SET DEFAULT false,
ALTER COLUMN "height" SET DATA TYPE TEXT,
ALTER COLUMN "weight" SET DATA TYPE TEXT,
ALTER COLUMN "smokingStatus" DROP NOT NULL,
ALTER COLUMN "smokingStatus" SET DEFAULT false,
ALTER COLUMN "dieteryPreference" DROP NOT NULL,
ALTER COLUMN "dieteryPreference" SET DATA TYPE TEXT,
ALTER COLUMN "pregnencyStatus" DROP NOT NULL,
ALTER COLUMN "pregnencyStatus" SET DEFAULT false,
ALTER COLUMN "mentalHealthHistory" DROP NOT NULL,
ALTER COLUMN "immunizationStatus" DROP NOT NULL,
ALTER COLUMN "hasPastSurgeries" DROP NOT NULL,
ALTER COLUMN "hasPastSurgeries" SET DEFAULT false,
ALTER COLUMN "recentAnxiety" DROP NOT NULL,
ALTER COLUMN "recentAnxiety" SET DEFAULT false,
ALTER COLUMN "recentDepression" DROP NOT NULL,
ALTER COLUMN "recentDepression" SET DEFAULT false,
ALTER COLUMN "maritalStatus" SET DEFAULT 'UNMARRIED',
ALTER COLUMN "createAt" DROP NOT NULL,
ALTER COLUMN "updateAt" DROP NOT NULL;
